const feedBack = [
    {   id: 1,
        idProduct: 1,
        idUser: 1,
        comment: 'ok, hàng đúng như hình, sẽ tiếp tục ủng hộ',
        date: '2022-03-0717:00',
        evaluate: 5
    },
    {   id: 2,
        idProduct: 2,
        idUser: 4,
        comment: 'ok, hàng đúng như hình, sẽ tiếp tục ủng hộ',
        date: '2022-03-0717:00',
        evaluate: 4
    },
    {   id: 3,
        idProduct: 4,
        idUser: 3,
        comment: 'ok, hàng đúng như hình, sẽ tiếp tục ủng hộ',
        date: '2022-03-0717:00',
        evaluate: 3
    },
    {   id: 4,
        idProduct: 2,
        idUser: 6,
        comment: 'ok, hàng đúng như hình, sẽ tiếp tục ủng hộ',
        date: '2022-03-0717:00',
        evaluate: 2
    },
    {   id: 5,
        idProduct: 6,
        idUser: 5,
        comment: 'ok, hàng đúng như hình, sẽ tiếp tục ủng hộ',
        date: '2022-03-0717:00',
        evaluate: 4
    },
    {   id: 6,
        idProduct: 2,
        idUser: 4,
        comment: 'ok, hàng đúng như hình, sẽ tiếp tục ủng hộ',
        date: '2022-03-0717:00',
        evaluate: 5
    },
    {   id: 7,
        idProduct: 3,
        idUser: 3,
        comment: 'ok, hàng đúng như hình, sẽ tiếp tục ủng hộ',
        date: '2022-03-0717:00',
        evaluate: 5
    },
    {   id: 8,
        idProduct: 1,
        idUser: 2,
        comment: 'ok, hàng đúng như hình, sẽ tiếp tục ủng hộ',
        date: '2022-03-0717:00',
        evaluate: 3
    },
    {   id: 9,
        idProduct: 2,
        idUser: 2,
        comment: 'ok, hàng đúng như hình, sẽ tiếp tục ủng hộ',
        date: '2022-03-0717:00',
        evaluate: 4
    },
    {   id: 10,
        idProduct: 2,
        idUser: 2,
        comment: 'ok, hàng đúng như hình, sẽ tiếp tục ủng hộ',
        date: '2022-03-0717:00',
        evaluate: 2
    },
]
export default feedBack;