const imagesProduct = [
    {   id: 1,
        idProduct: 1,
        img: './images/product/img1.jpg',
    },
    {   id: 2,
        idProduct: 2,
        img: './images/product/img2.jpg',
    },
    {   id: 3,
        idProduct: 3,
        img: './images/product/img3.jpg',
    },
    {   id: 4,
        idProduct: 4,
        img: './images/product/img4.jpg',
        price: '150.000 VND'
    },
    {   id: 5,
        idProduct: 5,
        img: './images/product/img5.jpg',
    },
    {   id: 6,
        idProduct: 5,
        img: './images/product/img1.jpg',
    },
    {   id: 7,
        idProduct: 4,
        img: './images/product/img2.jpg',
    },
    {   id: 8,
        idProduct: 3,
        img: './images/product/img2.jpg',
    },
    {   id: 9,
        idProduct: 2,
        img: './images/product/img4.jpg',
    },
    {   id: 10,
        idProduct: 10,
        img: './images/product/img5.jpg',
    },
]
export default imagesProduct;