const imagesFeedBack = [
    {   id: 1,
        idFeedBack: 1,
        img: './images/product/img1.jpg',
    },
    {   id: 2,
        idFeedBack: 2,
        img: './images/product/img2.jpg',
    },
    {   id: 3,
        idFeedBack: 3,
        img: './images/product/img3.jpg',
    },
    {   id: 4,
        idFeedBack: 4,
        img: './images/product/img4.jpg',
        price: '150.000 VND'
    },
    {   id: 5,
        idFeedBack: 5,
        img: './images/product/img5.jpg',
    },
    {   id: 6,
        idFeedBack: 5,
        img: './images/product/img1.jpg',
    },
    {   id: 7,
        idFeedBack: 4,
        img: './images/product/img2.jpg',
    },
    {   id: 8,
        idFeedBack: 3,
        img: './images/product/img2.jpg',
    },
    {   id: 9,
        idFeedBack: 2,
        img: './images/product/img4.jpg',
    },
    {   id: 10,
        idFeedBack: 10,
        img: './images/product/img5.jpg',
    },
]
export default imagesFeedBack;